1. android/key.properties (Para tu PC local)
Crea este archivo manualmente en la ruta tu_proyecto/android/key.properties.




keyAlias=aquí_tu_alias_real
keyPassword=aquí_tu_password_de_la_llave
storePassword=aquí_tu_password_del_keystore
storeFile=upload-keystore.jks
